name: Celebrate Release

on:
  release:
    types: [published]

jobs:
  celebrate:
    name: Celebrate Published Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ship-n-eat Action
        uses: ./
        with:
          dd-cli-token: ${{ secrets.DD_CLI_TOKEN }}
          dd-cli-email: ${{ secrets.DD_CLI_EMAIL }}
          dd-cli-password: ${{ secrets.DD_CLI_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
